openapi: 3.0.3
info:
  title: Example service
  description: Example service
  version: 1.0.0
servers:
  - url: 'https://'
paths:
  /products:
    get:
      description: Find all products
      operationId: findProducts
      parameters:
        - in: query
          name: locale
          required: false
          schema:
            type: Locale
      responses:
        200:
          description: Successful response
    post:
      description: Save new product
      operationId: saveProduct
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        200:
          description: Product saved successfully
components:
  schemas:
    Product:
      type: object
      properties:
        model:
          type: string
        name:
          type: string
        locale:
          type: Locale
        address1:
          type: Address
        address:
          $ref: '#/components/schemas/Address'
    Address:
      type: object
